### ISSUE TITLE
youtube video

### ISSUE THREAD

**Issue by angelhtml** [Crypto-Adhyeta/Signal-Stoch-RSI-MACD#1]
hi,can you send me your youtube video?

**Comment by Crypto-Adhyeta** [comment]
Hi there, here is the link to the video https://youtu.be/hh3BKTFE1dc. it isn't mine I just created the indicator following the video..... Haven't backtested it yet if it really works. good luck!

**Comment by angelhtml** [comment]
thank you so much 👍
